services:
  backend: 
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/backend
    container_name: backend
    depends_on:
      postgresql:
          condition: service_healthy
  
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - persist-volume:/var/lib/postgresql/data
      - ./backend/postgres/db.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./backend/.env
    container_name: postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U streamuser -d starstream_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    container_name: frontend
    depends_on:
      - postgresql
      - backend

  nms:
    build: ./nms 
    # image: giaongo/streaming_server
    ports:
      - "1935:1935"
      - "8000:8000"
      - "8443:8443"
    env_file: ./nms/.env
    volumes:
      - ./nms:/nms
      - /nms/node_modules
    container_name: nms

volumes:
  persist-volume: