services:
  backend: 
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/backend
    env_file: ./backend/.env
    container_name: backend
    depends_on:
      postgresql:
          condition: service_healthy
  
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - persist-volume:/var/lib/postgresql/data
      - ./postgres/db.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./backend/.env
    container_name: postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U streamuser -d starstream_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    container_name: frontend
    depends_on:
      - postgresql
      - backend

  nms:
    build: ./nms 
    ports:
      - "1935:1935"
      - "8000:8000"
      - "8443:8443"
    env_file: ./nms/.env
    volumes:
      - ./nms:/nms
      - ./nms/media:/nms/media:rw
      - /nms/node_modules
    container_name: nms
    depends_on:
      - whisper

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    volumes:
      - ./nms/model:/root/.cache/whisper
    container_name: whisper

  video_chat: 
    build: ./videochat
    ports: 
      - "5002:5002"
    volumes:
      - ./videochat/src:/videochat/src
      - persist-imagebind-model:/videochat/.checkpoints
    container_name: video_chat


volumes:
  persist-volume:
  persist-imagebind-model: