services:
  backend: 
    build: ./backend
    ports:
      - "5001:5001"
    # volumes:
    #   - ./backend:/backend
    env_file: ./backend/.env
    container_name: backend
    depends_on:
      postgresql:
          condition: service_healthy
  
  postgresql:
    # image: postgres
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - persist-volume:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    container_name: postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U streamuser -d starstream_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      # - "5173:5173"
      - 80:80
    # volumes:
    #   - ./frontend:/frontend
    #   - /frontend/node_modules
    container_name: frontend
    depends_on:
      - postgresql
      - backend

  nms:
    build:
      context: ./nms
      dockerfile: Dockerfile.prod
    # image: giaongo/streaming_server
    ports:
      - "1935:1935"
      - "8000:8000"
      - "8443:8443"
    env_file: ./nms/.env
    volumes:
      - ./nms/media:/nms/media:rw
    container_name: nms

volumes:
  persist-volume: