services:
  backend: 
    image: giaongo/starstream-backend:1.0
    ports:
      - "5001:5001"
    env_file: .env
    container_name: backend
    depends_on:
      postgresql:
          condition: service_healthy
    environment:
      POSTGRES_URL: "postgresql:5432"
  
  postgresql:
    image: giaongo/starstream-postgres:1.0
    ports:
      - "5432:5432"
    volumes:
      - persist-volume:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U streamuser -d starstream_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: giaongo/starstream-frontend:1.0
    ports:
      - "80:80"
      - "443:443"
    container_name: frontend
    depends_on:
      - postgresql
      - backend

volumes:
  persist-volume: